# Generated by Django 5.1.4 on 2025-01-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_employee_department_remove_employee_user'),
        ('departments', '0002_alter_department_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
